#!/bin/bash

echo "Informe o usuário:"
 read usuario
	`cut -f 1,5 -d ":" /etc/passwd | grep $usuario > /dev/null`
	  if [ $? -eq 0 ]; then
	  	echo "$usuario é cadastrado" 
	  else
	  	echo "$usuario não é cadastrado"
	  fi	
